version: '3.9'

services:
  app_api:
    build: ./app_api
    container_name: api_service
    ports:
      - "8003:8000"
    networks:
      - front-api
      - api-db
    depends_on:
      - db
    env_file:
      - .env
    

  app_front:
    build: ./app_front
    container_name: front_service
    ports:
      - "8502:8501"
    networks:
      - front-api
    env_file:
      - .env
  
  db:
    image: postgres:15
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - api-db

volumes:
  db_data:

networks:
  front-api:
  api-db: