name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  api-test-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install 3.11

      - name: Install API dependencies
        working-directory: app_api
        run: uv sync

      - name: Lint API with Ruff
        working-directory: app_api
        run: |
          uv run ruff check .
          uv run ruff format --check .

      - name: Run tests with Pytest
        working-directory: app_api
        run: uv run pytest tests


  front-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install 3.11

      - name: Install Streamlit dependencies
        working-directory: app_front
        run: uv sync

      - name: Lint Frontend with Ruff
        working-directory: app_front
        run: |
          uv run ruff check .
          uv run ruff format --check .
